### ISSUE TITLE
Novo valor do "Authorization"

### ISSUE THREAD

**Issue by gabrielguarisa** [ESEGroup/IssuesAuthenticatorJararaca#14]
Recebemos o valor do campo Authorizathion igual a Basic NDpwYXNzd29yZA==.
Entretanto, quando executamos os testes recebemos o status code HTTP/1.1 401 UNAUTHORIZED.
Solicitamos um novo valor válido para realizar os testes.

**Comment by gabrielsoldani** [comment]
Você pode usar o usuário "4" e a senha "nada" (sem aspas).

```Authorization: Basic NDpuYWRh```
