### ISSUE TITLE
Possíveis links para realizar o teste

### ISSUE THREAD

**Issue by gabrielguarisa** [ESEGroup/IssuesAuthenticatorJararaca#15]
Não encontramos nenhum documento que possua os endereços e os campos das requisições do servidor REST. Só precisamos de uma base para realizar os testes.

**Comment by mdjunior** [comment]
Um endereço provisório para teste pode ser encontrado nos arquivos [JS](https://github.com/ESEGroup/IssuesAuthenticatorJararaca/blob/master/app/www/js/index.js#L50)
