### ISSUE TITLE
Registro de entrada e saída do aplicativo

### ISSUE THREAD

**Issue by imarcia** [ESEGroup/IssuesAuthenticatorJararaca#18]
Os registros podem ser feitos várias vezes com sucesso de forma consecutiva.

**Comment by mdjunior** [comment]
Nós especificamos na [documentação de interoperabilidade](https://github.com/ESEGroup/IssuesAuthenticatorJararaca/wiki/Documenta%C3%A7%C3%A3o-de-Interoperabilidade#post-authenticatorentradalab) que a API falharia silenciosamente.
